/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_turingq_eesdk_EESdk */

#ifndef _Included_com_turingq_eesdk_EESdk
#define _Included_com_turingq_eesdk_EESdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_turingq_eesdk_EESdk
 * Method:    createClient
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_turingq_eesdk_EESdk_createClient
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_turingq_eesdk_EESdk
 * Method:    destroyClient
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_turingq_eesdk_EESdk_destroyClient
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_turingq_eesdk_EESdk
 * Method:    requestCertificate
 * Signature: (JLcom/turingq/eesdk/CertificateRequest;)Lcom/turingq/eesdk/CertificateResponse;
 */
JNIEXPORT jobject JNICALL Java_com_turingq_eesdk_EESdk_requestCertificate
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_turingq_eesdk_EESdk
 * Method:    requestCertificateWithPKCS10
 * Signature: (J[B)Lcom/turingq/eesdk/CertificateResponse;
 */
JNIEXPORT jobject JNICALL Java_com_turingq_eesdk_EESdk_requestCertificateWithPKCS10
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_turingq_eesdk_EESdk
 * Method:    revokeCertificate
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_turingq_eesdk_EESdk_revokeCertificate
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_turingq_eesdk_EESdk
 * Method:    confirmCertificate
 * Signature: (J[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_turingq_eesdk_EESdk_confirmCertificate
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
