/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_turingq_eesdk_EESdk */

#ifndef _Included_com_turingq_eesdk_EESdk
#define _Included_com_turingq_eesdk_EESdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_turingq_eesdk_EESdk
 * Method:    createClient
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_com_turingq_eesdk_EESdk_createClient
  (JNIEnv *, jclass, jstring, jstring, jint, jint);

/*
 * Class:     com_turingq_eesdk_EESdk
 * Method:    destroyClient
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_turingq_eesdk_EESdk_destroyClient
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_turingq_eesdk_EESdk
 * Method:    executeRequest
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/turingq/eesdk/Response;
 */
JNIEXPORT jobject JNICALL Java_com_turingq_eesdk_EESdk_executeRequest
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     com_turingq_eesdk_EESdk
 * Method:    healthCheck
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_turingq_eesdk_EESdk_healthCheck
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
